# Generated by Django 5.0.2 on 2024-04-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_farmer_product_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
